version: '3.8'

services:
  glpi-webhook:
    build: .
    container_name: glpi-webhook-server
    ports:
      - "8507:5000"
    environment:
      - FLASK_ENV=production
      - MATTERMOST_API_URL=http://192.168.1.10:8065/api/v4
      - MATTERMOST_TOKEN=w9kkmo1wpty37mtqudrt6jrfmc
      - MATTERMOST_CHANNEL_ID=y846awehtpnw3q8uh54zq8r9ta
      - MATTERMOST_BOT_ID=qufjhxr9yjfqfx99jgsquuq1ey
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - glpi-network

networks:
  glpi-network:
    driver: bridge
